[project]
name = "checkpoint"
version = "0.0.1"
authors = [
  {name = "Kohei Miyaguchi", email = "koheimiyaguchi@gmail.com"},
]
license = {text = "MIT License"}
requires-python = ">=3.9"
dependencies = [
    "sqlitedict~=2.1.0",
    "typing_extensions",
    "dill",
    "pytest",
]
